#!/bin/bash

echo "====================================="
echo "SELLER DASHBOARD VERIFICATION"
echo "====================================="
echo ""
echo "Login credentials to use:"
echo "Email: seller@test.com"
echo "Password: C@rlos2025"
echo ""
echo "The Financial Accounts card should show:"
echo "1. View Banking Details button"
echo "2. View Payment Account button"
echo "3. View Crypto Wallets button"
echo ""
echo "Additionally, below those buttons you should see:"
echo "- Personal Bank Account section"
echo "- EUR Payment Account (Striga) with IBAN: PT500035060900000987fa37"
echo "- Crypto Wallets section"
echo ""
echo "URL to check: http://95.179.170.56:3019/seller/dashboard"
echo ""
echo "====================================="
